### ISSUE TITLE
rules expressions documentation

### ISSUE THREAD

**Issue by anshibanov** [ItsNotGoodName/smtpbridge#1]
First of all, thank you very much for this amazing project.

A big request - could you please provide a little more detailed information on the compilation rules expressions? 
I mean:

```
rules:
  example_rule:
    name: Example Rule
    expression: or (eq .Message.Subject "cam-1") (eq .Message.Subject "cam-2") <---- This is
```

What variables are available? A few complex examples would be very helpful
